### ISSUE TITLE
Incorrect documentation on disprec and fform

### ISSUE THREAD

**Issue by joshlevinson** [tflanagan/node-quickbase#13]
Thanks for this library–it's a huge timesaver!
I found that some bits of the documentation are correct: The references to [API_AddRecord](https://github.com/tflanagan/node-quickbase/blob/master/documentation/api.md#api_addrecord) imply that specifying `disprec: false` and `fform: false` in options is the correct way to set those values. However, Quickbase appears to base its response solely on the _presence_ of those options, not the value. Setting those to `false` (or presumably _any_ value) is effectively the same as setting them to `1`–the response is a redirect to the form of the newly added record.

What do you think the best way of documenting those parameters is?

**Comment by tflanagan** [comment]
Hey @joshlevinson, thanks for the feedback!

Yea, parts of QuickBase's API are pretty quirky. I think the best option is to copy what QuickBase says about them (which is why I give a link to their documentation):

"Omit this property if you don't want the new record to display within the QuickBase application."
"Omit this property if you don't need QuickBase to set Checkbox fields based on your HTML page."

Adding these as comments next to the key/pair in the docs should be fine. Care to send in a PR?

**Comment by tflanagan** [comment]
I've migrated documentation to a new website:

https://www.quickbase.dev/
