### ISSUE TITLE
AddRecord & EditRecord bug: The API request successfully adds/edits the record as expected but it returns an empty response

### ISSUE THREAD

**Issue by jagarcia29** [tflanagan/node-quickbase#15]
Has anyone else run into this?

I need to store the record ID of the record I am adding. Until I figure out why the API request is returning a blank response, I am using webhooks to catch when a record is added and field matching it to the record without a record ID in my application. This approach is obviously not ideal. I would appreciate some help figuring out why AddRecord and EditRecord are returning empty responses. My code for AddRecord is pasted below:

```
quickbase.api('API_AddRecord',{
            dbid: external.content.api.dbid,
            fields: external.clone.fields,
            disprec: true,
            msInUTC: false,
            ignoreError: false,
            udata: "Record added by Qipo"
        }).then((results) => {
            console.log("DEBUG: results returned from Quickbase.AddRecord: ",results);
            resolve(results);
            /* results = {
             * 	action: 'API_AddRecord',
             * 	errcode: 0,
             * 	errtext: 'No error',
             * 	rid: 21,
             * 	update_id: 1206177014451
             * }
             */
        }).catch( (error) => {
            console.log("QuickbaseAPI.AddRecord Error: ",error);
            reject(new Error(error));
        });
```

**Comment by tflanagan** [comment]
Hey,

I have not run into this before, are you able to see find any errors?

Before executing your code, could you set the environment variable "debug" to "quickbase:*" and report the logged output?

`set debug=quickbase:*`

Thanks,

**Comment by tflanagan** [comment]
Haven't heard anything, I'm assuming you found the solution in your implementation.

**Comment by robwhite4** [comment]
I recently ran into this same problem.  I know this issue is closed, but there does seem to be an issue somewhere.  I hope I can help, but I must say upfront that I'm not a professional developer, just a hobby-hacker.  ;)

So, I'm using the Add_Record method in an express app.  Running locally for testing, here is my output from the logs (cleaned up a bit for ease of reading):

```
quickbase:request 0 {
hostname: 'hiddenToProtectTheInnocent.quickbase.com',
port: 443,
path: '/db/hiddenToProtectTheInnocent?act=API_AddRecord',
method: 'POST',
headers: {
'Content-Type': 'application/xml; charset=ISO-8859-1',
'QUICKBASE-ACTION': 'API_AddRecord'
},
agent: false
}
<?xml version="1.0" encoding="UTF-8"?>
<qdbapi>
<dbid>hiddenToProtectTheInnocent</dbid>
<disprec>false</disprec>
<fform>false</fform>
<ignoreError>false</ignoreError>
<msInUTC>false</msInUTC>
<usertoken>hiddenToProtectTheInnocent</usertoken>
<encoding>ISO-8859-1</encoding>
<field fid="14">John</field>
<field fid="16">Doe</field>
<field fid="56" />
<field fid="53" />
<field fid="206">none</field>
<field fid="207">None</field>
<field fid="208">None</field>
<field fid="25" />
<field fid="26" />
<field fid="210">john@doe.com</field>
<field fid="209">$2b$12$nu0/b.uaPqUrUGx1l9RsXOJk5MSZAgy9/r2RAidgfyy.IkyakYTYa</field>
<field fid="211">on</field>
<field fid="212">on</field>
</qdbapi> +0ms
quickbase: response 0  +387ms

quickbase:request 1{
hostname: 'hiddenToProtectTheInnocent.quickbase.com',
port: 443,
path: '/db/hiddenToProtectTheInnocent?act=API_AddRecord',
method: 'POST',
headers:
{ 'Content-Type': 'application/xml; charset=ISO-8859-1',
'QUICKBASE-ACTION': 'API_AddRecord' },
agent: false }
<?xml version="1.0" encoding="UTF-8"?>
<qdbapi>
<dbid>hiddenToProtectTheInnocent</dbid>
<disprec>false</disprec>
<fform>false</fform>
<ignoreError>false</ignoreError>
<msInUTC>false</msInUTC>
<usertoken>hiddenToProtectTheInnocent</usertoken>
<encoding>ISO-8859-1</encoding>
<field fid="14">John</field>
<field fid="16">Doe</field>
<field fid="56">C555555</field>
<field fid="53">55</field>
<field fid="206">dual</field>
<field fid="207">Grade 3</field>
<field fid="208">Grade 2</field>
<field fid="25">(555) 555-5555</field>
<field fid="26">(555) 555-5555</field>
<field fid="210">john@doe.com</field>
<field fid="209">$2b$12$NyxdsknIwA3Sk/Mdrk.rqOP/JAE35nDop.f3lDSYFx3XXnzFqBmba</field>
<field fid="211">on</field>
<field fid="212">on</field>
</qdbapi> +14m
quickbase:response 1  +562ms
```
There are two attempts at adding records detailed above.  I've removed some data so as not to share any secrets.  There is no response from either.  If I try to log the response to the console, I don't get _undefined_ or anything.  Just a blank spot where some choice data should be. 

I am wondering if there might be an issue with SSL, stemming from the **port:443** feedback up there ^^.

Again, I'm not a true dev, but that line sticks out to me given the difficulty Chrome has recently introduced in firing up a secure localhost.  I'm probably wrong, but if not I'm going to use my guess as proof to my dev friends that I'm better than they are at life in general..  haha

I hope this provides you some info so we can figure this out.  I have a workaround in mind, but it would be nice to just feed that rid into my sessions or wherever else from the result of this type of call. 

Please let me know if I can be of further assistance.  

I love this package!!  Thank you so much for creating it!  :)

~Rob

**Comment by robwhite4** [comment]
I forgot to also mention that the records *_are successfully added_* to QuickBase.

Just FYI.

Thanks again,

~Rob
